GestionMusiques/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('musiques/', include('musiques.urls')),
]

musiques/urls.py
from django.urls import path
from .views import ArtisteCreate, ArtisteDelete, ArtisteDetail, ArtisteList, ArtisteUpdate, MorceauDetail, MorceauList, MorceauCreate, MorceauUpdate, MorceauDelete, morceau_detail
from musiques import views

#app_name = 'musiques' # Encapsule les urls de ce module dans le namespace musique

urlpatterns = [
    path('morceaux', MorceauList.as_view(), name='morceaux'),
    path('morceau/<int:pk>', MorceauDetail.as_view(), name='morceau'),
    path('<int:pk>', morceau_detail, name='morceau-detail'),
    path('morceau/create', MorceauCreate.as_view(), name='morceau-create'),
    path('morceau/update/<int:pk>', MorceauUpdate.as_view(), name='morceau-update'),
    path('morceau/delete/<int:pk>', MorceauDelete.as_view(), name='morceau-delete'),

    path('artistes/', ArtisteList.as_view(), name='artistes'),    
    path('artiste/<int:pk>', ArtisteDetail.as_view(), name='artiste'),
    path('artiste/create/', ArtisteCreate.as_view(), name='artiste-create'),
    path('artiste/update/<int:pk>', ArtisteUpdate.as_view(), name='artiste-update'),
    path('artiste/delete/<int:pk>', ArtisteDelete.as_view(), name='artiste-delete'),
    
]

musiques/models.py
from django.db import models


# Create your models here.

class Artiste(models.Model):
    nom = models.CharField(max_length=64)

    def __str__(self):
        return self.nom
    
class Morceau(models.Model):
    titre = models.CharField(max_length=64)
    date_sortie = models.DateField(null=True)
    fk_artiste = models.ForeignKey(Artiste,on_delete=models.CASCADE, null=False)

    def __str__(self):
        return '{self.titre} ({self.fk_artiste.nom})'.format(self=self)
    
   
    


    

musiques/views.py
from typing import Any, Dict
from django.db import models
from django.shortcuts import render
from django.http import HttpResponse
from .models import Morceau,Artiste
from django.views.generic import DetailView,ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.
def morceau_detail(request,pk):
    return HttpResponse('OK')

def artiste_detail(request,pk):
    return HttpResponse('OK')

###################################" CRUD Morceau ##########################"

class MorceauDetail(DetailView):
    model = Morceau
    context_object_name = 'morceaux'

class MorceauList(ListView):
    model = Morceau
    context_object_name = 'morceaux'

class MorceauCreate(CreateView):
    model = Morceau
    fields = ['titre','date_sortie','fk_artiste']
    success_url = reverse_lazy('morceaux')   

    def get_context_data(self, **kwargs):
        context = super(MorceauCreate, self).get_context_data(**kwargs)
        lesA = Artiste.objects.all().values()
        context ['mesArtistes']= lesA     
        return context      
    
    def form_valid(self, form):
        messages.success(self.request, "Le morceau a été créé avec succès.")
        return super(MorceauUpdate,self).form_valid(form)

class MorceauUpdate(UpdateView):
    
    model=Morceau
    fields = ['titre','date_sortie','fk_artiste']
    success_url = reverse_lazy('morceaux')   

    def get_context_data(self, **kwargs):
        context = super(MorceauUpdate, self).get_context_data(**kwargs)
        lesA = Artiste.objects.all().values()
        context ['mesArtistes']= lesA        
        return context     
    
    def form_valid(self, form):
        messages.success(self.request, "Le morceau a été mis à jour avec succès.")
        return super(MorceauUpdate,self).form_valid(form)
    
class MorceauDelete(DeleteView):
    model = Artiste
    context_object_name = 'morceau'
    success_url = reverse_lazy('morceaux')

    def form_valid(self, form):
        messages.success(self.request, "Le morceau a été supprimé avec succès.")
        return super(MorceauDelete,self).form_valid(form)
    
###################################" CRUD Artiste ##########################"
class ArtisteDetail(DetailView):
    model = Artiste
    context_object_name = 'artistes'

class ArtisteList(ListView):
    model = Artiste
    context_object_name = 'artistes'

class ArtisteCreate(CreateView):
    model = Artiste
    fields = ['nom']    
    success_url = reverse_lazy('artistes')
    
    def form_valid(self, form):
        messages.success(self.request, "L'artiste a été créé avec succès.")
        return super(ArtisteCreate,self).form_valid(form)
    
class ArtisteUpdate(UpdateView):
    model = Artiste
    fields = ['nom']
    success_url = reverse_lazy('artistes')
    
    def form_valid(self, form):
        messages.success(self.request, "Le nom de l'artiste a été mis à jour avec succès.")
        return super(ArtisteUpdate,self).form_valid(form)
    
class ArtisteDelete(DeleteView):
    model = Artiste
    context_object_name = 'artiste'
    success_url = reverse_lazy('artistes')

    def form_valid(self, form):
        messages.success(self.request, "L'artiste a été supprimé avec succès.")
        return super(ArtisteDelete,self).form_valid(form)
    
    
    

musiques/templates/base.html
<!doctype html>
{% load static %}
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        {% block metas %}
        <meta name="viewport" content="width=device-width,initial-scale =1,shrink-to-fit=no">
        {% endblock %}
        {% block styles %}
        <link rel="stylesheet" href="{% static 'css/mon.css' %}">
        <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
       
        {% endblock %}
    </head>
    <body>
            {% block nav %}
            <nav class="nav">
                {% block navtitle %}{% endblock %}
                <a href="{% url 'artistes' %}"><i class="bi bi-list-task"></i>Mes Artistes</a>
                <a href="{% url 'artiste-create' %}"><i class="bi bi-plus-circle"></i>Créer un artiste</a>
                <a href="{% url 'morceaux' %}"><i class="bi bi-list-task"></i>Mes Morceaux</a>
                <a href="{% url 'morceau-create' %}"><i class="bi bi-plus-circle"></i>Créer un morceau</a>
            </nav>
            {% endblock %}
            <main role="main" class="container top-pushed">
                <div class="container">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}}">
                                {{message}}
                                </div>
                            {% endfor %}
                        {% endif %}
                    <div class="jumbotron">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </main >
            
            <footer class="footer">
                <div class="container">
                   <p>&copy; Copyright {% now "Y" %} by Titof Production Copyrigh (c)</p>
                </div>
            </footer>
        {% block js %}
        <!--script src="{% static 'node_modules/jquery-slim/dist/jquery-slim.min.js' %}"></script>
        <script src="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.js' %}"></script>
        <script src="{% static 'node_modules/popper.js/dist/popper.min.js' %}"></script-->
        {% endblock %}
    </body>
</html>

musiques/templates/musiques/artiste_confirm_delete.html
{%extends 'base.html'%}

{%block content%}
<div class="center">
	<form method="post" class="card">
		{% csrf_token %}
		<h2>Suppression d'un artiste</h2>
		<p>Etes vous sûr de vouloir supprimer l'artiste "{{object.nom}}"?</p>
		<p class="form-buttons">
			<input type="submit" class="btn btn-primary" value="Supprimer">
			<a href="{% url 'artistes' %}" class="btn btn-outline">Annuler</a>
		</p>
	</form>
</div>

{%endblock content%}

musiques/templates/musiques/artiste_detail.html
{%extends 'base.html'%}

{% block title %}
Application Musiques
{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous">
{% endblock %}

{%block content%}
<article class="task">
	<header>
            <h2>Détail de l'artiste</h2>
            <p>{{object.nom}}</p>
      </header>
</article>
{%endblock content%}

musiques/templates/musiques/artiste_form.html
{%extends 'base.html'%}

{% block title %}
Application Musiques
{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous">
{% endblock %}

{%block content%}

<div class="center">
	<form method="post" novalidate class="card">
		{%csrf_token %}
		<h2>{% if artiste %} Mise à jour {%else %} Création {%endif%} d'un artiste</h2>
		{% for field in form %}
			{% if field.name == 'completed' %}
				<p>
					{{ field.label_tag }}
					{{ field }}
				</p>
				{% if field.errors %}
					<small class="error">{{ field.errors|striptags  }}</small> 
				{% endif %}
			{% else %}
				{{ field.label_tag }} 
				{{ field }}
				{% if field.errors %}
					<small class="error">{{ field.errors|striptags  }}</small> 
				{% endif %}
			{% endif %}
		{% endfor %}
		
		<div class="form-buttons">
			<input type="submit" value="Sauvegarder" class="btn btn-primary"/>
			<a href="{%url 'artistes'%}" class="btn btn-outline">Annuler</a>
		</div>
	</form>
</div>

{%endblock content%}

musiques/templates/musiques/artiste_list.html
{%extends 'base.html'%}

{% block title %}
Application Musiques
{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous">
{% endblock %}

{%block content%}

<div class="center">
	<h2>Mes Artistes</h2>
	{% if artistes %}
	<ul class="tasks">
		{% for artiste in artistes %}
            
			<li><a href="{% url 'artiste' artiste.id %}">{{ artiste.nom }}</a>
				<div class="task-controls">
					<a href="{%url 'artiste-delete' artiste.id %}"><i class="fas fa-trash"></i></a>
					<a href="{%url 'artiste-update' artiste.id %}"><i class="fas fa-pen"></i></a>		     
				</div>
			</li>
		{% endfor %}
    </ul>
	{% else %}
		<p>🎉 Il n'y a aucun artiste en base ! <a href="{%url 'artiste-create'%}">Créer un artiste</a></p>
	{% endif %}
	
</div>
{%endblock content%}

musiques/templates/musiques/morceau_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

musiques/templates/musiques/morceau_detail.html
{%extends 'base.html'%}

{% block title %}
Application Musiques
{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous">
{% endblock %}

{%block content%}
<article class="task">
	<header>
        <h2>Détail du morceau</h2>
        <li>Titre : {{object.titre}}</li>
        {% if object.date_sortie %}
        <li>Date de sortie : {{object.date_sortie}}</li>
        {% endif %}
        <li>Interprète : {{object.fk_artiste.nom}}</li>
    </header>
</article>    
{%endblock content%}

musiques/templates/musiques/morceau_form.html
{%extends 'base.html'%}

{% block title %}
Application Musiques
{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous">
{% endblock %}

{%block content%}

<div class="center">
 <form method="post" novalidate class="card">
 	{%csrf_token %}
 	<h2>{% if morceau %} Mise à jour {%else %} Création {%endif%} d'un morceau</h2>
    <label for="id_titre">Titre:</label>
    <input type="text" name="titre" value="{{ morceau.titre }}" maxlength="64" required id="id_titre">
   
    <label for="id_date_sortie">Date sortie:</label>
    {% if morceau.date_sortie.value %} 
    <input type="date" name="date_sortie" value="{{ morceau.date_sortie }}" id="id_date_sortie">
    {%else%}
    <input type="date" name="date_sortie" value="" id="id_date_sortie">
    {%endif%}
    
    {% if morceau %}
        <label for="id_fk_artiste">Interprète</label> 
        <select name="fk_artiste" required id="id_fk_artiste">
            <option value="">---------</option>
            {% for artiste in mesArtistes %}
                {% if artiste.nom == morceau.fk_artiste.nom %}
                        <option value="{{artiste.id}}"  selected>{{artiste.nom}}</option>
                {% else %}
                        <option value="{{artiste.id}}">{{artiste.nom}}</option>
                {% endif %}
            {% endfor %}
        </select>
    {%else %}
    <label for="id_fk_artiste">Interprète</label> 
    <select name="fk_artiste" required id="id_fk_artiste">
        <option value="">---------</option>
        {% for artiste in mesArtistes %}
            <option value="{{artiste.id}}">{{artiste.nom}}</option>
        {% endfor %}
    </select>
    {% endif %}

    <div class="form-buttons">
		<input type="submit" value="Sauvegarder" class="btn btn-primary"/>
		<a href="{%url 'morceaux'%}" class="btn btn-outline">Annuler</a>
	</div>
	

</form>
</div>

{%endblock content%}

musiques/templates/musiques/morceau_list.html
{%extends 'base.html'%}

{% block title %}
Application Musiques
{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous">
{% endblock %}

{%block content%}

<div class="center">
	<h2>Mes Morceaux</h2>
	{% if morceaux %}
	<ul class="tasks">
		{% for morceau in morceaux %}
            <li>
			    <a href="{% url 'morceau' morceau.id %}">{{ morceau.titre }}</a>
                <div class="task-controls">
					<a href="{%url 'morceau-delete' morceau.id %}"><i class="fas fa-trash"></i></a>
					<a href="{%url 'morceau-update' morceau.id %}"><i class="fas fa-pen"></i></a>
				</div>		     
			</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>🎉 Il n'y a aucun morceau en base ! <a href="{%url 'morceau-create'%}">Créer un morceau</a></p>
	{% endif %}
	
</div>
{%endblock content%}

musiques/templates/musiques/morceau_update_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>